{% set name = "empyrical" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantopian/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2d0265546fdb90793bcbb1708b7232f4d744a0ca5f1ba04cc0c2dde2b8af389c
  patches:
    - 0001_fix_tests.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
  run:
    - python
    # Need to limit numpy version: AttributeError: `np.NINF` was removed in the NumPy 2.0 release. Use `-np.inf` instead.
    - numpy >=1.9.2,<2.0.0
    - pandas >=0.16.1
    - scipy >=0.15.1
    - six
    - pandas-datareader >=0.2

test:
  source_files:
    - empyrical
    - runtests.py
  imports:
    - empyrical
    - empyrical.tests
  requires:
    - pip
    - nose >=1.3.7
    - parameterized >=0.6.1
  commands:
    - pip check
    - python -c "from importlib.metadata import version as v; assert v('empyrical')=='{{ version }}'"
    - ./runtests.py

about:
  home: https://github.com/quantopian/empyrical
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: empyrical is a Python library with performance and risk statistics commonly used in quantitative finance
  description: |
    empyrical is a Python library with performance and risk
    statistics commonly used in quantitative finance by Quantopian Inc
  dev_url: https://github.com/quantopian/empyrical
  doc_url: https://quantopian.github.io/empyrical

extra:
  recipe-maintainers:
    - alen12345
    - fawce
    - gerrymanoim
    - jbredeche
    - jdricklefs
    - llllllllll
    - richafrank
